# Generated by Django 5.1.6 on 2025-06-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_curriculum_status_movies"),
    ]

    operations = [
        migrations.AddField(
            model_name="movies",
            name="title",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
