# Generated by Django 5.1.6 on 2025-06-03 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_movies_title"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Movies",
            new_name="Movie",
        ),
    ]
