# Generated by Django 5.1.6 on 2025-06-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_rename_movies_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
