# Generated by Django 5.1.6 on 2025-06-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_movie_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="curriculum",
            name="detail",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="feedback",
            field=models.IntegerField(default=3),
        ),
    ]
